name: "nesrak1"

url: '' 
baseurl: ''

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
    input: GFM
    syntax_highlighter: rouge

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: /pages/page-:num

source: .
destination: ./_site

sass:
    style: :compressed
    sass_dir: assets/css/

